CM-334: change how benefit plan is filtered in picker
openimis/openimis-fe-social_protection_js pull request #50
Opened 2023-10-04 16:00 UTC by jdolkowski

https://openimis.atlassian.net/browse/CM-334

It needs: https://github.com/openimis/openimis-be-social_protection_py/pull/37

2023-10-04 16:11 UTC, dborowiecki requested changes
@jdolkowski this change also contains alphabetical order feature which I think should be implemented on backend (or at least merged in separate PR). Can you fix it?

2023-10-04 20:29 UTC, jdolkowski commented
I fixed it

2023-10-05 08:35 UTC, sniedzielski approved these changes

2023-10-05 08:43 UTC, sniedzielski approved these changes

2023-10-05 08:48 UTC, sniedzielski approved these changes

2023-10-05 08:54 UTC, sniedzielski approved these changes

2023-10-05 19:39 UTC, dborowiecki approved these changes

2023-10-05 19:39 UTC, merged